import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics Book
  bookSidebar: [
    {
      type: 'category',
      label: 'Introduction',
      items: ['intro'],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System (ROS 2)',
      items: [
        'module-1-ros2/index',
        'module-1-ros2/chapter-1-middleware',
        'module-1-ros2/chapter-2-communication',
        'module-1-ros2/chapter-3-ai-bridge',
        'module-1-ros2/chapter-4-urdf',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin (Gazebo & Unity)',
      items: [
        'module-2-digital-twin/index',
        'module-2-digital-twin/chapter-1-digital-twins',
        'module-2-digital-twin/chapter-2-gazebo-physics',
        'module-2-digital-twin/chapter-3-unity-visualization',
        'module-2-digital-twin/chapter-4-sensor-simulation',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
      items: [
        'module-3-ai-brain/index',
        'module-3-ai-brain/chapter-1-ai-brain',
        'module-3-ai-brain/chapter-2-isaac-sim',
        'module-3-ai-brain/chapter-3-perception-navigation',
        'module-3-ai-brain/chapter-4-nav2-path-planning',
        'module-3-ai-brain/chapter-5-training-perception',
        'module-3-ai-brain/diagrams',
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action (VLA)',
      items: [
        'module-4-vla/index',
        'module-4-vla/chapter-1-vla-intro',
        'module-4-vla/chapter-2-voice-to-action',
        'module-4-vla/chapter-3-cognitive-planning',
        'module-4-vla/chapter-4-capstone',
        'module-4-vla/diagrams',
      ],
    },
  ],
};

export default sidebars;
